# This is a basic workflow to help you get started with Actions

name: Deploy Service

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Deploy Application'
        required: true
        default: 'build_deploy'
    
defaults:
  run:
    working-directory: backend

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install and Build 🔧
        run:
          mvn clean install
#       - name: Install Heroku
#         run: sudo snap install --classic heroku
#       - name: Herku Login
#         run: |
#           cat > ~/.netrc <<EOF
#             machine api.heroku.com
#               login $HEROKU_EMAIL
#               password $HEROKU_API_KEY
#             machine git.heroku.com
#               login $HEROKU_USER_EMAIL
#               password $HEROKU_API_KEY
#           EOF
#         env:
#           HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Heroku Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run:  |
              heroku plugins:install java
              heroku deploy:jar target/*.jar --app auth-app-service
          
